### ISSUE TITLE
Mod compatibility checklist

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#593]
- [x] Chatterer v0.9.91
- [x] Docking Port Alignment Indicator v6.5.1
- [ ] Ferram Aerospace Research ~~v0.15.7.2~~
- [x] Kerbal Alarm Clock v3.8.0
- [x] MechJeb v2.6.0
- [ ] Pilot Assistant v1.13.0 - untested
- [x] RealChute v1.4.1.2

**Comment by DeputyLOL** [comment]
Looks like pilot assistance still works

**Comment by MOARdV** [comment]
> Looks like pilot assistance still works

Good to know.  FWIW, I have dusted off MAS and started looking at it again.  Not sure when I'll finish MFD features for it, but maybe I can get a more-official build out this summer.
